# Generated by Django 4.1.2 on 2022-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='last_name',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='name',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
